AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DYNAMODB_ENDPOINT_OVERRIDE: ""
        USERS_TABLE_NAME: "scoring-service-users"

Resources:
  SubscribeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SubscribeFunction
      Handler: subscribe.App::handleRequest
      Runtime: java8
      MemorySize: 256
      Events:
        Subscribe:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /subscribe
            Method: post
      Policies:
        DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: scoring-service-users
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SubscribeApi:
    Description: "API Gateway endpoint URL for Prod stage for Subscribe function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscribe/"
  SubscribeFunction:
    Description: "Subscribe Lambda Function ARN"
    Value: !GetAtt SubscribeFunction.Arn
  SubscribeFunctionIamRole:
    Description: "Implicit IAM Role created for Subscribe function"
    Value: !GetAtt SubscribeFunction.Arn
